return function(c, hl)
  hl("lualine_a_normal", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("lualine_a_insert", { fg = c.on_primary, bg = c.tertiary, bold = true })
  hl("lualine_a_visual", { fg = c.on_primary, bg = c.secondary, bold = true })
  hl("lualine_a_replace", { fg = c.surface, bg = c.error, bold = true })
  hl("lualine_a_command", { fg = c.on_primary, bg = c.secondary_container, bold = true })
  hl("lualine_b_normal", { fg = c.on_surface_variant, bg = c.surface_container })
  hl("lualine_c_normal", { fg = c.outline, bg = nil })
  hl("lualine_b_diagnostics_error", { fg = c.error, bg = c.surface_container })
  hl("lualine_b_diagnostics_warn", { fg = c.tertiary, bg = c.surface_container })
  hl("lualine_b_diagnostics_info", { fg = c.secondary, bg = c.surface_container })
  hl("lualine_b_diagnostics_hint", { fg = c.primary, bg = c.surface_container })
end
