#font_family JetBrains Mono
font_family JetBrainsMono Nerd Font Mono

#bold_font JetBrains Mono Bold
#italic_font JetBrains Mono Italic
#bold_italic_font JetBrains Mono Bold Italic

bold_font JetBrainsMono Nerd Font Mono Extra Bold
italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic

font_size 13.0

map ctrl+up increase_font_size
map ctrl+down decrease_font_size

hide_window_decorations no

map F11 toggle_fullscreen

window_padding_width 12

#include wallust/colors.conf
#include matugen/colors.conf


# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
