# --- Main Colors ---
background            #15130c
foreground            #e7e2d5
cursor                #e7e2d5
cursor_text_color     #15130c

selection_background  #4b472b
selection_foreground  #ebe3bd

url_color             #a7d0b7

# --- ANSI Colors ---
color0                #15130c
color1                #ffb4ab
color2                #a7d0b7
color3                #cec7a3
color4                #d4c871
color5                #a7d0b7
color6                #cec7a3
color7                #e7e2d5

color8                #4a473a
color9                #93000a
color10               #294e3b
color11               #4b472b
color12               #4f4700
color13               #4b472b
color14               #294e3b
color15               #ccc6b5

# --- Starship Prompt Bubbles ---
color255              #4f4700
color254              #d4c871
color253              #4b472b
color252              #cec7a3
color251              #294e3b
color250              #a7d0b7
color249              #93000a
color248              #ffb4ab

color232              #f1e48a
color233              #373100
color234              #ebe3bd
color235              #343117
color236              #c2ecd3
color237              #103726
color238              #ffdad6
color239              #690005
color240              #f1e48a

# Matched with unthemed light/dark
color243              #d4c871
color244              #ffb4ab
color245              #4a473a

# --- UI Elements ---
active_tab_foreground   #373100
active_tab_background   #d4c871
inactive_tab_foreground #f1e48a
inactive_tab_background #4f4700

active_border_color     #d4c871
inactive_border_color   #959181

# --- Marks ---
mark1_foreground        #201c00
mark1_background        #f1e48a
mark2_foreground        #1f1c05
mark2_background        #ebe3bd
mark3_foreground        #002113
mark3_background        #c2ecd3
