source = ~/.cache/iris/colors-hypr.conf
source = ~/.cache/wallust/wllppr.conf

general {
    hide_cursor = false
    ignore_empty_input = true
}

animations {
    enabled = true
}

# ---------- Background ----------
background {
    monitor =
    
    path = $wallpaper
    blur_passes = 3
    blur_size = 8
    # noise = 0.015
    # contrast = 1.05
    vibrancy = 0.1696
    vibrancy_darkness = 1.1
}

# ---------- Clock ----------
label {
    monitor =
    text = $TIME
    font_size = 100
    font_family = Adwaita Sans Black
    color = $fg #rgba(255, 255, 255, 0.6)
    position = 0, 130
    halign = center
    valign = center
}

# image {
#     monitor = 
#     path = ~/.config/hypr/terminal.png
#     border_size = 0
#     position = 0, 0
#     size = 500
#     rounding = 0
#     halign = left
#     valign = top
# }

label {
    monitor =
    text = cmd[update:10000] echo "$(neofetch --stdout --cpu_speed off --cpu_temp C --memory_percent on --package_managers off --disable gpu icons theme shell song title packages kernel term --underline off)"
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    color = $fg #rgba(31, 42, 31, 0.6)
    position = 20, -20
    halign = left
    valign = top
}

# ---------- Date ----------
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d %B %Y')"
    font_size = 34
    font_family = Adwaita Sans Bold
    color = $accent #rgba(255, 255, 255, 0.6)
    position = 0, 40
    halign = center
    valign = center
}

# ---------- Keyboard Layout ----------
label {
    monitor = eDP-1
    text = $LAYOUT [$ATTEMPTS] $FAIL
    font_size = 18
    font_family = Adwaita Sans Medium
    color = $fg #rgba(250, 250, 250, 0.8)

    position = 20, 20
    halign = left
    valign = bottom
}

# ---------- Sleep Button ----------
label {
    monitor =
    text = 󰒲
    font_size = 30
    font_family = JetBrainsMono Nerd Font
    color = $fg #rgba(250, 250, 250, 0.8)

    position = -20, 20
    halign = right
    valign = bottom

    onclick = systemctl suspend
}


input-field {
    monitor =
    size = 200, 50
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding

    inner_color = $bg #$primary
    font_color = $fg #$on_primary

    font_family = JetBrainsMono Nerd Font #Fira Semibold

    outer_color = $surface #$on_primary

    outline_thickness = 3
    fade_on_empty = true
    fade_timeout = 1000 # Milliseconds before fade_on_empty is triggered.
    placeholder_text = Input Password... # Text rendered in the input box when it's empty.
    hide_input = false
    rounding = 10 # -1 means complete rounding (circle/oval)

    check_color = $accent #$primary
    fail_color = $red #$error # if authentication failed, changes outer_color and fail message color

    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
    invert_numlock = false # change color if numlock is off
    swap_font_color = false # see below
    position = 0, -40
    halign = center
    valign = center
    shadow_passes = 10
    shadow_size = 40

    shadow_color = $surface #entry_border_color #$shadow

    shadow_boost = 1.6
}

# ---------- Slack Unread ----------
#label {
#    monitor =
#    text = cmd[update:30] ~/.config/hypr/slack.sh
#    font_size = 18
#    font_family = JetBrainsMono Nerd Font
#    color = rgba(250, 250, 250, 0.8)
#
#    position = 0, -40
#    halign = center
#    valign = top
#}
